server:
  port: 9999
debug: true
spring:
  datasource:
    name: peach
    url: jdbc:mysql://127.0.0.1:3306/taojie
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: livvy
    driver-class-name: com.mysql.jdbc.Driver


  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.lvy.wwt.domain
logging:
  level: info
